# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-11 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_auto_20190311_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
