# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-11 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_picture_uploaded_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='profile',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='profile_details',
        ),
    ]
